# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Quantum Mechanics
title-normal: FTC Team 6051
email: youremailaddress@gmail.com
description: "We are a robotics team based out of The Dalton School in New York City."
baseurl: "" # the subpath of your site, e.g. /blog
author: 
street_address: The Dalton School<br \>108 East 89th Street
city: New York
state: NY
zip_code: 10128
country: United States of America
phone: (212) 423-5200

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 15

# Social settings
500px_url: 
facebook_url: https://www.facebook.com/quantum6051/
github_url: https://github.com/quantummechanics6051
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url:
pinterest_url: 
slack_url: https://dalton.slack.com
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
